# zmodload zsh/zpr
# exports {
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=true
export CLAUDE_TELEMETRY_ENABLED=false
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export EDITOR=nvim
export FCEDIT=nvim
export HOMEBREW_NO_ENV_HINTS=1
export LESS=" -R "
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LSCOLORS=ExfxcxdxBxegedabagacad
export SHELL_SESSIONS_DISABLE=1
export SUDO_EDITOR=nvim
export VISUAL=nvim
HISTDUP=erase
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=$HISTSIZE
# }
# options {
setopt GLOB_COMPLETE
setopt appendhistory
setopt autocd
setopt correct
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt interactivecomments
setopt magicequalsubst
setopt nonomatch
setopt notify
setopt numericglobsort
setopt promptsubst
setopt sharehistory
# }
# keybinds {
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# Enable substring matching
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
# }
# path {
export PATH=/opt/homebrew/bin:$PATH
export PATH="/Users/edison/.local/bin:$PATH"
export PATH="/Users/edison/.lmstudio/bin:$PATH"
export PATH="/Users/edison/.antigravity/antigravity/bin:$PATH"
# }
# sdkman {
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
# }
# plugins {
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(fzf --zsh)"
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source "/opt/homebrew/opt/fzf-tab/share/fzf-tab/fzf-tab.zsh"
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi
# }
# alias {
alias c='clear'
alias cp='cp -iv'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fk='thefuck'
alias grep='grep --color=auto'
alias j='z'
alias kubectl='kubecolor'
alias less='less -m -N -g -i -J --underline-special --SILENT'
alias list='eza -bghl --git --icons --color=automatic'
alias ls='eza --icons'
alias mkdir='mkdir -pv'
alias more='less'
alias mv='mv -iv'
alias q='exit'
alias quit='exit'
alias rm='rm -iv'
alias rmdir='rmdir -v'
alias rg='rg --smart-case --hidden'
alias tail='tspin'
alias vi='nvim'
alias vim='nvim'
# }
#
# functions {
nvm() {
    unset -f nvm node npm npx
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
    [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
    nvm "$@"
}

node() {
    unset -f nvm node npm npx
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
    node "$@"
}

npm() {
    unset -f nvm node npm npx
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
    npm "$@"
}

npx() {
    unset -f nvm node npm npx
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
    npx "$@"
}
# }
# zprof
# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
