
alias ant='ant -logger org.apache.tools.ant.listener.AnsiColorLogger'
alias ct='pygmentize -O style=borland'
alias editor='nvim'
alias fp='ps aux | grep'
alias gP='git push'
alias gf='git flush'
alias gp='git pull'
alias gs='git status'
alias j='z'
alias kubectl='kubecolor'
alias list="eza -bghl --git --icons --color=automatic"
alias ls='eza --icons'
alias nano='nvim'
alias vi='nvim'
alias vim='nvim'
